module.exports = {
  tableData: [
    {
      id: 1,
      selected: false,
      exam: "ULTRASSOM",
      status: "FINALIZADO"
    }
    // {
    //   id: 2,
    //   selected: false,
    //   exam: "TOMOGRAFIA",
    //   status: "À LAUDAR"
    // },
    // {
    //   id: 3,
    //   selected: false,
    //   exam: "ROTINA",
    //   status: "AGENDADO"
    // }
  ],
  columnsReports: [
    {
      name: "readphyfullname",
      required: true,
      label: "Médico Responsável",
      align: "left",
      field: "readphyfullname",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "creationdate",
      required: true,
      label: "Versão",
      align: "left",
      field: "creationdate",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "username",
      required: true,
      label: "Usuário",
      align: "left",
      field: "username",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "status",
      required: true,
      label: "Status",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "update",
      required: true,
      label: "Editar",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    }
  ],
  tableDataReports: [
    {
      id: "188",
      uuid: "0c94d832-a756-48f9-9843-8f884dabbab7",
      studyuuid: "8603e119-c530-486d-ab0c-a94c63b14d81",
      studydescription: "ULTRASSOM - GINECOLÓGICO ENDOVAGINAL",
      creationdate: "2019-04-21T12:25:14.380Z",
      username: "MASTER",
      completed: true,
      workstationid: "1",
      workstationuui: "b0abdb43-32af-42c4-9c95-7eeeabb10482",
      workstationalias: "USG-01-L",
      workstationfullname: "SALA USG 01 - LAUDOS",
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null
    },
    {
      id: "187",
      uuid: "7f6c4975-6304-49db-aa55-64696fdc450d",
      studyuuid: "8603e119-c530-486d-ab0c-a94c63b14d81",
      studydescription: "ULTRASSOM - GINECOLÓGICO ENDOVAGINAL",
      creationdate: "2019-04-20T22:12:54.670Z",
      username: "MASTER",
      completed: true,
      workstationid: "1",
      workstationuui: "b0abdb43-32af-42c4-9c95-7eeeabb10482",
      workstationalias: "USG-01-L",
      workstationfullname: "SALA USG 01 - LAUDOS",
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null
    },
    {
      id: "185",
      uuid: "510b2e20-2408-4af3-8d51-e6d7a1f3ff14",
      studyuuid: "8603e119-c530-486d-ab0c-a94c63b14d81",
      studydescription: "ULTRASSOM - GINECOLÓGICO ENDOVAGINAL",
      creationdate: "2018-12-13T18:41:23.929Z",
      username: "MASTER",
      completed: true,
      workstationid: "1",
      workstationuui: "b0abdb43-32af-42c4-9c95-7eeeabb10482",
      workstationalias: "USG-01-L",
      workstationfullname: "SALA USG 01 - LAUDOS",
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null
    }
  ],
  columnsHistoryExams: [
    {
      name: "studydescription",
      required: true,
      label: "Exame",
      align: "left",
      field: "studydescription",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "statusname",
      required: true,
      label: "Status",
      align: "left",
      field: "statusname",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    
    {
      name: "readphyid",
      required: true,
      label: "Laudo",
      align: "left",
      field: "readphyid",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "totalimages",
      required: true,
      label: "Imagens",
      align: "left",
      field: "totalimages",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "open",
      required: true,
      label: "Abrir",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    }
  ],
  tableDataHistoryExams: [
    {
      id: "f7ef7adeb5fab6d6f3e61038f08d3aa8",
      accessionnumber: "202030078",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016646400",
      studydescription: "ULTRASSOM - GINECOLÓGICO ENDOVAGINAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:40:30",
      patientid: "1046576",
      patientname: "PEDRINA CELISMARA GIROTTO",
      patientbirthdate: "1965-07-10T03:00:00.000Z",
      patientage: 53,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUIZ ANTONIO BUGALHO",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "59",
      studyuuid: "8603e119-c530-486d-ab0c-a94c63b14d81",
      groupuuid: null,
      ordergroupuuid: "8603e119-c530-486d-ab0c-a94c63b14d81",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030078&patientid=1046576&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: "1",
      workstationuuid: "b0abdb43-32af-42c4-9c95-7eeeabb10482",
      workstationalias: "USG-01-L",
      workstationname: "SALA USG 01 - LAUDOS",
      perfphyid: "3",
      perfphyuuid: "564ff945-f627-4ac6-87fc-077207328ed0",
      perfphyregistrytype: "CRM",
      perfphyregistryid: "7791",
      perfphyregistryuf: "SP",
      perfphyfirstname: "AMADEU",
      perfphyfullname: "AMADEU GONCALVES",
      studyannotations: "gsdgsd",
      reportid: "188",
      reportuuid: "0c94d832-a756-48f9-9843-8f884dabbab7",
      reportcreationdate: "2019-04-21T12:25:14.380Z",
      reportusername: "MASTER",
      reportcompleted: true,
      reportcloneuuid: null,
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "3"
    },
    {
      id: "c98533ee7534e1737745b7b56520d4ac",
      accessionnumber: "202030076",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016647600",
      studydescription: "ULTRASSOM - MAMA(S)",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:47:26",
      patientid: "1046576",
      patientname: "PEDRINA CELISMARA GIROTTO",
      patientbirthdate: "1965-07-10T03:00:00.000Z",
      patientage: 53,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUIZ ANTONIO BUGALHO",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "60",
      studyuuid: "c55a3bee-e67f-4a2c-b17a-ebdd6b8b97a4",
      groupuuid: null,
      ordergroupuuid: "c55a3bee-e67f-4a2c-b17a-ebdd6b8b97a4",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030076&patientid=1046576&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: "3",
      workstationuuid: "528d90c4-5f50-413e-a74a-f41ddf4a80a8",
      workstationalias: "USG-03-T",
      workstationname: "SALA USG 03 - TERREO",
      perfphyid: "5",
      perfphyuuid: "053f9235-a19e-4a61-ab88-60c7f46a5871",
      perfphyregistrytype: "CRM",
      perfphyregistryid: "4664",
      perfphyregistryuf: "SP",
      perfphyfirstname: "JESSICA",
      perfphyfullname: "JESSICA ANTUNES",
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "3"
    },
    {
      id: "2be81c073967f56cbdeab9feef1fd690",
      accessionnumber: "202030074",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66603737600",
      studydescription: "ULTRASSOM - ABDOME TOTAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:23:00",
      patientid: "1046576",
      patientname: "PEDRINA CELISMARA GIROTTO",
      patientbirthdate: "1965-07-10T03:00:00.000Z",
      patientage: 53,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUIZ ANTONIO BUGALHO",
      creationdate: "2018-08-15T19:25:06.000Z",
      totalimages: "18",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "58",
      studyuuid: "f0e4b1c4-72e5-486b-83f7-d8e9f4f89be2",
      groupuuid: null,
      ordergroupuuid: "f0e4b1c4-72e5-486b-83f7-d8e9f4f89be2",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030074&patientid=1046576&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "3"
    }
  ],
  columns: [
    {
      name: "exam",
      required: true,
      label: "Exame",
      align: "left",
      field: "exam",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "status",
      required: true,
      label: "Status",
      align: "left",
      field: "status",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "vincular",
      required: true,
      label: "Vincular",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "report",
      required: true,
      label: "Relatório",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "images",
      required: true,
      label: "Imagens",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "open",
      required: true,
      label: "Abrir",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    }
  ],
  columnsAttachments: [
    {
      name: "type",
      required: true,
      label: "Tipo de Documento",
      align: "left",
      field: "type",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "user",
      required: true,
      label: "Usuário",
      align: "left",
      field: "user",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "date",
      required: true,
      label: "Data",
      align: "left",
      field: "date",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "open",
      label: "Abrir",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "action",
      label: "Ação",
      align: "left",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    }
  ],
  tableDataAttachments: [
    {
      type: "HISTÓRICO CLÍNICO",
      user: "Flavio",
      date: new Date("2019-05-06")
    }
  ]
};
