module.exports = {
  tableData: [
    {
      id: "f7ef7adeb5fab6d6f3e61038f08d3aa8",
      accessionnumber: "202030078",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016646400",
      studydescription: "ULTRASSOM - GINECOLÓGICO ENDOVAGINAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:40:30",
      patientid: "1046576",
      patientname: "PEDRINA CELISMARA GIROTTO",
      patientbirthdate: "1965-07-10T03:00:00.000Z",
      patientage: 53,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUIZ ANTONIO BUGALHO",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "59",
      studyuuid: "8603e119-c530-486d-ab0c-a94c63b14d81",
      groupuuid: null,
      ordergroupuuid: "8603e119-c530-486d-ab0c-a94c63b14d81",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030078&patientid=1046576&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: "1",
      workstationuuid: "b0abdb43-32af-42c4-9c95-7eeeabb10482",
      workstationalias: "USG-01-L",
      workstationname: "SALA USG 01 - LAUDOS",
      perfphyid: "3",
      perfphyuuid: "564ff945-f627-4ac6-87fc-077207328ed0",
      perfphyregistrytype: "CRM",
      perfphyregistryid: "7791",
      perfphyregistryuf: "SP",
      perfphyfirstname: "AMADEU",
      perfphyfullname: "AMADEU GONCALVES",
      studyannotations: "gsdgsd",
      reportid: "188",
      reportuuid: "0c94d832-a756-48f9-9843-8f884dabbab7",
      reportcreationdate: "2019-04-21T12:25:14.380Z",
      reportusername: "MASTER",
      reportcompleted: true,
      reportcloneuuid: null,
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "424f857afb63bfe5f8cd6c62dcd80832",
      accessionnumber: "202032424",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016644700",
      studydescription: "ULTRASSOM - GINECOLÓGICO ENDOVAGINAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "09:23:35",
      patientid: "1123247",
      patientname: "MARIA APARECIDA DE BRITO MIRANDA",
      patientbirthdate: "1967-11-20T02:00:00.000Z",
      patientage: 51,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "SHEILA MARIA G PELAEZ",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "62",
      studyuuid: "2eaec78c-a08c-4b2c-b3c1-d52ae6f90c11",
      groupuuid: null,
      ordergroupuuid: "2eaec78c-a08c-4b2c-b3c1-d52ae6f90c11",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202032424&patientid=1123247&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: "1",
      workstationuuid: "b0abdb43-32af-42c4-9c95-7eeeabb10482",
      workstationalias: "USG-01-L",
      workstationname: "SALA USG 01 - LAUDOS",
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: "190",
      reportuuid: "0be85020-2a66-4f87-bb7f-07404689bfda",
      reportcreationdate: "2019-05-13T16:58:02.634Z",
      reportusername: "MASTER",
      reportcompleted: true,
      reportcloneuuid: "c2c94750-eaee-4c81-be5b-308b10dc8467",
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "c98533ee7534e1737745b7b56520d4ac",
      accessionnumber: "202030076",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016647600",
      studydescription: "ULTRASSOM - MAMA(S)",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:47:26",
      patientid: "1046576",
      patientname: "PEDRINA CELISMARA GIROTTO",
      patientbirthdate: "1965-07-10T03:00:00.000Z",
      patientage: 53,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUIZ ANTONIO BUGALHO",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "60",
      studyuuid: "c55a3bee-e67f-4a2c-b17a-ebdd6b8b97a4",
      groupuuid: null,
      ordergroupuuid: "c55a3bee-e67f-4a2c-b17a-ebdd6b8b97a4",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030076&patientid=1046576&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: "3",
      workstationuuid: "528d90c4-5f50-413e-a74a-f41ddf4a80a8",
      workstationalias: "USG-03-T",
      workstationname: "SALA USG 03 - TERREO",
      perfphyid: "5",
      perfphyuuid: "053f9235-a19e-4a61-ab88-60c7f46a5871",
      perfphyregistrytype: "CRM",
      perfphyregistryid: "4664",
      perfphyregistryuf: "SP",
      perfphyfirstname: "JESSICA",
      perfphyfullname: "JESSICA ANTUNES",
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "2be81c073967f56cbdeab9feef1fd690",
      accessionnumber: "202030074",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66603737600",
      studydescription: "ULTRASSOM - ABDOME TOTAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:23:00",
      patientid: "1046576",
      patientname: "PEDRINA CELISMARA GIROTTO",
      patientbirthdate: "1965-07-10T03:00:00.000Z",
      patientage: 53,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUIZ ANTONIO BUGALHO",
      creationdate: "2018-08-15T19:25:06.000Z",
      totalimages: "18",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "58",
      studyuuid: "f0e4b1c4-72e5-486b-83f7-d8e9f4f89be2",
      groupuuid: null,
      ordergroupuuid: "f0e4b1c4-72e5-486b-83f7-d8e9f4f89be2",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030074&patientid=1046576&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "f5c8364275567e7b46d7591660a61db4",
      accessionnumber: "202032425",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016645300",
      studydescription: "ULTRASSOM - MAMA(S)",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "09:26:56",
      patientid: "1123247",
      patientname: "MARIA APARECIDA DE BRITO MIRANDA",
      patientbirthdate: "1967-11-20T02:00:00.000Z",
      patientage: 51,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "ODELIO VILARINHO PRUDENCIO",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "61",
      studyuuid: "75bb3ca8-518a-4b75-b7c2-9775d11151ee",
      groupuuid: null,
      ordergroupuuid: "75bb3ca8-518a-4b75-b7c2-9775d11151ee",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202032425&patientid=1123247&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: "189",
      reportuuid: "7c1ba911-0b68-49f4-88ad-316294413d61",
      reportcreationdate: "2019-05-13T16:58:02.638Z",
      reportusername: "MASTER",
      reportcompleted: true,
      reportcloneuuid: "c2c94750-eaee-4c81-be5b-308b10dc8467",
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "557673483577448d9cb7be77f5bab736",
      accessionnumber: "202030326",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016499301",
      studydescription: "ULTRASSOM - DOPPLER COLOR DE AORTA E ARTÉRIAS RENAIS",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:23:31",
      patientid: "2016624",
      patientname: "ANGELA MARIA GIGLIO ANDREATTA",
      patientbirthdate: "1959-12-30T03:00:00.000Z",
      patientage: 59,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "DR TESTE",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030326&patientid=2016624&networkid=DASA",
      statusid: "1",
      statusname: "AGENDADO",
      statustype: "SCHEDULED",
      statusweight: 10,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "6d5ac05fda0f2a225b24e720327b7863",
      accessionnumber: "202030675",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66603694400",
      studydescription: "ABDOMEN",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "09:30:43",
      patientid: "1800056662",
      patientname: "DIRCE FERREIRA DOS SANTOS",
      patientbirthdate: "1968-06-17T03:00:00.000Z",
      patientage: 50,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "GRACIELA LONGO TOFANO",
      creationdate: "2018-08-15T19:19:25.000Z",
      totalimages: "12",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030675&patientid=1800056662&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "bdad6596d429b3c28d65aef2d8f27be4",
      accessionnumber: "202026415",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66603573100",
      studydescription: "ULTRASSOM - ABDOME TOTAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "09:07:15",
      patientid: "1123247",
      patientname: "MARIA APARECIDA DE BRITO MIRANDA",
      patientbirthdate: "1967-11-20T02:00:00.000Z",
      patientage: 51,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "ODELIO VILARINHO PRUDENCIO",
      creationdate: "2018-08-15T19:24:16.000Z",
      totalimages: "18",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "52",
      studyuuid: "24205ccf-8928-411c-acdf-70f59d3dc63a",
      groupuuid: null,
      ordergroupuuid: "24205ccf-8928-411c-acdf-70f59d3dc63a",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202026415&patientid=1123247&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: "183",
      reportuuid: "c2c94750-eaee-4c81-be5b-308b10dc8467",
      reportcreationdate: "2018-08-15T20:43:07.357Z",
      reportusername: "MASTER",
      reportcompleted: true,
      reportcloneuuid: null,
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "7d1569306a3875f84586d358fbea4383",
      accessionnumber: "202032423",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66603579500",
      studydescription: "ULTRASSOM - APARELHO URINÁRIO FEMININO",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "09:30:14",
      patientid: "1123247",
      patientname: "MARIA APARECIDA DE BRITO MIRANDA",
      patientbirthdate: "1967-11-20T02:00:00.000Z",
      patientage: 51,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "ODELIO VILARINHO PRUDENCIO",
      creationdate: "2018-08-15T19:24:32.000Z",
      totalimages: "6",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: "63",
      studyuuid: "c72fbc5c-23be-4797-bbc4-af186a85366a",
      groupuuid: null,
      ordergroupuuid: "c72fbc5c-23be-4797-bbc4-af186a85366a",
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202032423&patientid=1123247&networkid=DASA",
      statusid: "8",
      statusname: "FINALIZADO",
      statustype: "COMPLETED",
      statusweight: 80,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: "1",
      readphyuuid: "7ea332b8-f3a7-47ec-ad84-76d6c183928d",
      readphyregistrytype: "CRM",
      readphyregistryid: "1234",
      readphyregistryuf: "SP",
      readphyfirstname: "JORGE LIMA",
      readphyfullname: "JORGE LIMA",
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "ff45b59bca06b8256d552ac1e3c93262",
      accessionnumber: "202028699",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66493974402",
      studydescription: "ULTRASSOM - APARELHO URINÁRIO FEMININO",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:05:48",
      patientid: "2016624",
      patientname: "ANGELA MARIA GIGLIO ANDREATTA",
      patientbirthdate: "1959-12-30T03:00:00.000Z",
      patientage: 59,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: null,
      creationdate: "2018-08-15T18:59:52.000Z",
      totalimages: "12",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202028699&patientid=2016624&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "1dc580103594b84a3ec072b0ae578dcf",
      accessionnumber: "202028696",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016499300",
      studydescription:
        "ULTRASSOM - DOPPLER COLOR DE VASOS CERVICAIS ARTERIAIS BILATERAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "10:27:15",
      patientid: "2016624",
      patientname: "ANGELA MARIA GIGLIO ANDREATTA",
      patientbirthdate: "1959-12-30T03:00:00.000Z",
      patientage: 59,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "DR TESTE",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202028696&patientid=2016624&networkid=DASA",
      statusid: "1",
      statusname: "AGENDADO",
      statustype: "SCHEDULED",
      statusweight: 10,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "2623d3a5de67e3cc1a95e44a85562b05",
      accessionnumber: "202030673",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66603692800",
      studydescription: "ENDO-VAGINAL",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "09:42:26",
      patientid: "1800056662",
      patientname: "DIRCE FERREIRA DOS SANTOS",
      patientbirthdate: "1968-06-17T03:00:00.000Z",
      patientage: 50,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "GRACIELA LONGO TOFANO",
      creationdate: "2018-08-15T19:19:19.000Z",
      totalimages: "6",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030673&patientid=1800056662&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "c79f36a268a305ee211737c8e8049c7c",
      accessionnumber: "202030671",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66603691200",
      studydescription: "BREAST",
      studydate: "2018-03-27T03:00:00.000Z",
      studytime: "09:49:41",
      patientid: "1800056662",
      patientname: "DIRCE FERREIRA DOS SANTOS",
      patientbirthdate: "1968-06-17T03:00:00.000Z",
      patientage: 50,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "GRACIELA LONGO TOFANO",
      creationdate: "2018-08-15T19:19:15.000Z",
      totalimages: "18",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030671&patientid=1800056662&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "532b17464f4e0056e83d594f170ee01a",
      accessionnumber: "202030322",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016640000",
      studydescription: "ULTRASSOM - ORGÃOS SUPERFICIAIS",
      studydate: "2018-03-26T03:00:00.000Z",
      studytime: "11:11:45",
      patientid: "1126797",
      patientname: "FRANCISCO ROMEIRO SETUVAL",
      patientbirthdate: "1953-07-20T03:00:00.000Z",
      patientage: 65,
      patientsex: "MASCULINO",
      referphyregistryid: "",
      referphyfullname: "GIOVANA BEATRIZ A CARVALHO",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202030322&patientid=1126797&networkid=DASA",
      statusid: "1",
      statusname: "AGENDADO",
      statustype: "SCHEDULED",
      statusweight: 10,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "c4ec8febd65c426eb1b2acafc604d555",
      accessionnumber: "202031523",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016516600",
      studydescription: "ULTRASSOM - TIREÓIDE",
      studydate: "2018-03-26T03:00:00.000Z",
      studytime: "09:28:48",
      patientid: "1800067773",
      patientname: "NADYR CONCEICAO COELHO DELSIN",
      patientbirthdate: "1941-02-15T03:00:00.000Z",
      patientage: 78,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "ELVIRA HELENA MILAN LISE",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202031523&patientid=1800067773&networkid=DASA",
      statusid: "1",
      statusname: "AGENDADO",
      statustype: "SCHEDULED",
      statusweight: 10,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "565a897f6f4e077a91f4eeeefe315ee7",
      accessionnumber: "202032307",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016513100",
      studydescription: "ULTRASSOM - ORGÃOS ESTRUTURAS SUPERFICIAIS",
      studydate: "2018-03-26T03:00:00.000Z",
      studytime: "14:44:57",
      patientid: "2011583",
      patientname: "VILMA DE SOUZA TURATO",
      patientbirthdate: "1951-02-24T02:00:00.000Z",
      patientage: 68,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUCIANA JACCOUD ESCHER",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202032307&patientid=2011583&networkid=DASA",
      statusid: "1",
      statusname: "AGENDADO",
      statustype: "SCHEDULED",
      statusweight: 10,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "98b1134756407ba69aec152a7be9c89d",
      accessionnumber: "202031519",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016516000",
      studydescription: "ULTRASSOM - MAMA(S)",
      studydate: "2018-03-26T03:00:00.000Z",
      studytime: "09:59:17",
      patientid: "1800067773",
      patientname: "NADYR CONCEICAO COELHO DELSIN",
      patientbirthdate: "1941-02-15T03:00:00.000Z",
      patientage: 78,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "ELVIRA HELENA MILAN LISE",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202031519&patientid=1800067773&networkid=DASA",
      statusid: "1",
      statusname: "AGENDADO",
      statustype: "SCHEDULED",
      statusweight: 10,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "4fe86c34e344571a253d57835c8a9d8e",
      accessionnumber: "202032304",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66595727200",
      studydescription: "ULTRASSOM - GINECOLÓGICO ENDOVAGINAL",
      studydate: "2018-03-26T03:00:00.000Z",
      studytime: "14:53:13",
      patientid: "2011583",
      patientname: "VILMA DE SOUZA TURATO",
      patientbirthdate: "1951-02-24T02:00:00.000Z",
      patientage: 68,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUCIANA JACCOUD ESCHER",
      creationdate: "2018-08-15T19:16:53.000Z",
      totalimages: "6",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202032304&patientid=2011583&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "8f4ba5eea45da984e0715128228bd267",
      accessionnumber: "202032305",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.172136271271756.66595730201",
      studydescription: "ULTRASSOM - MAMA(S)",
      studydate: "2018-03-26T03:00:00.000Z",
      studytime: "14:56:02",
      patientid: "2011583",
      patientname: "VILMA DE SOUZA TURATO",
      patientbirthdate: "1951-02-24T02:00:00.000Z",
      patientage: 68,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "LUCIANA JACCOUD ESCHER",
      creationdate: "2018-08-15T19:16:54.000Z",
      totalimages: "12",
      totalseries: "1",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202032305&patientid=2011583&networkid=DASA",
      statusid: "3",
      statusname: "A LAUDAR",
      statustype: "TOREAD",
      statusweight: 30,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    },
    {
      id: "3a28314c7d716423026ee8b5c73e4d78",
      accessionnumber: "202031525",
      studymodality: "US",
      studyinstanceuid: "2.16.124.113543.6022.1.18245943618171.68016514800",
      studydescription:
        "ULTRASSOM - DOPPLER COLOR DE VASOS CERVICAIS ARTERIAIS BILATERAL",
      studydate: "2018-03-26T03:00:00.000Z",
      studytime: "09:48:35",
      patientid: "1800067773",
      patientname: "NADYR CONCEICAO COELHO DELSIN",
      patientbirthdate: "1941-02-15T03:00:00.000Z",
      patientage: 78,
      patientsex: "FEMININO",
      referphyregistryid: "",
      referphyfullname: "ELVIRA HELENA MILAN LISE",
      creationdate: null,
      totalimages: "0",
      totalseries: "0",
      insurancename: "ALLIANZ SAUDE S.A",
      studyid: null,
      studyuuid: null,
      groupuuid: null,
      ordergroupuuid: null,
      studygrouped: false,
      siteid: "1",
      sitename: "DASA",
      networkid: "DASA",
      webviewerurl:
        "http://192.168.102.111:85/dsweb/printviewer.html?accnum=202031525&patientid=1800067773&networkid=DASA",
      statusid: "1",
      statusname: "AGENDADO",
      statustype: "SCHEDULED",
      statusweight: 10,
      workstationid: null,
      workstationuuid: null,
      workstationalias: null,
      workstationname: null,
      perfphyid: null,
      perfphyuuid: null,
      perfphyregistrytype: null,
      perfphyregistryid: null,
      perfphyregistryuf: null,
      perfphyfirstname: null,
      perfphyfullname: null,
      studyannotations: null,
      reportid: null,
      reportuuid: null,
      reportcreationdate: null,
      reportusername: null,
      reportcompleted: null,
      reportcloneuuid: null,
      readphyid: null,
      readphyuuid: null,
      readphyregistrytype: null,
      readphyregistryid: null,
      readphyregistryuf: null,
      readphyfirstname: null,
      readphyfullname: null,
      revphyid: null,
      revphyuuid: null,
      revphyregistrytype: null,
      revphyregistryid: null,
      revphyregistryuf: null,
      revphyfirstname: null,
      revphyfullname: null,
      rows: "49"
    }
  ],
  columns: [
    {
      name: "desc",
      label: "",
      required: true,
      align: "left"
    },
    {
      name: "info",
      label: "",
      required: true,
      align: "left"
    },
    {
      name: "patientid",
      label: "Identificação",
      align: "left",
      field: "patientid",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "paciente",
      label: "Paciente",
      align: "left",
      field: "patientname",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "sexo",
      label: "Sexo",
      align: "left",
      field: "patientsex",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "nascimento",
      label: "Nascimento",
      align: "left",
      field: "patientbirthdate",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "origem",
      label: "Origem",
      align: "left",
      field: "sitename",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "descricao",
      label: "Descrição do Exame",
      align: "left",
      field: "studydescription",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "mod",
      label: "Mod.",
      align: "left",
      field: "studymodality",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "dataExame",
      label: "Data do Exame",
      align: "left",
      field: "reportcreationdate",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    },
    {
      name: "status",
      label: "Status",
      align: "left",
      field: "statusname",
      sortable: true,
      classes: "my-class",
      style: "width: 500px"
    }
  ],
  visibleColumns: ['desc', 'info', 'patientid', 'paciente', 'sexo', 'nascimento', 'origem', 'origem', 'descricao', 'mod', 'dataExame', 'status'],
  columnsDoctorModal: [
    {
      name: "id",
      required: true,
      label: "Id",
      field: "id",
      align: "left"
    },
    {
      name: "doctorName",
      required: true,
      label: "Médico",
      field: "doctorName",
      align: "left"
    }
  ],
  columnsWorkStationModal: [
    {
      name: "code",
      required: true,
      label: "code",
      field: "code",
      align: "left"
    },
    {
      name: "workStationName",
      required: true,
      label: "workStationName",
      field: "workStationName",
      align: "left"
    }
  ],
  tableDataDoctorModal: [
    {
      id: 1,
      doctorName: "FLAVIO VINICIUS MIRANDA"
    },
    {
      id: 2,
      doctorName: "WILLIAM SAKAI"
    },
    {
      id: 3,
      doctorName: "MARCELO"
    }
  ],
  tableDataWorkStationModal: [
    {
      code: "USG - 5045",
      workStationName: "SALA 1"
    },
    {
      code: "USG - 6070",
      workStationName: "SALA 3"
    },
    {
      code: "USG - 3050",
      workStationName: "SALA 7"
    }
  ]
};
